version: '3'
services:
  app:
    container_name: reading-is-good
    image: reading-is-good
    build: ./
    ports:
      - "9091:9091"
    depends_on:
      - postgres-db
    networks:
      - my-network
    environment:
      SPRING_DATA_MONGODB_HOST: mongo-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: test
  postgres-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network: